# Generated by Django 5.2.6 on 2025-09-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
