# Generated by Django 5.2.6 on 2025-09-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories_app", "0003_category_created_at_category_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="similar_to",
            field=models.ManyToManyField(blank=True, to="categories_app.category"),
        ),
    ]
