# Color names understood by Graphviz.
# https://graphviz.org/doc/info/colors.html
# Colors are spread apart so the most distinguishable colors are first.
# Supports up to 50 rabbit islands as example.
X11_COLOR_NAMES = [
    "red",
    "green",
    "blue",
    "yellow",
    "cyan",
    "magenta",
    "white",
    "gray",
    "orange",
    "brown",
    "limegreen",
    "royalblue",
    "deeppink",
    "gold",
    "darkgreen",
    "indigo",
    "turquoise",
    "firebrick",
    "slateblue",
    "darkorange",
    "chocolate",
    "forestgreen",
    "dodgerblue",
    "violet",
    "orchid",
    "peru",
    "tomato",
    "khaki",
    "darkkhaki",
    "mediumseagreen",
    "mediumturquoise",
    "deepskyblue",
    "mediumblue",
    "blueviolet",
    "mediumvioletred",
    "hotpink",
    "indianred",
    "lightcoral",
    "palevioletred",
    "mediumpurple",
    "darkcyan",
    "lightseagreen",
    "saddlebrown",
    "sienna",
    "oliveDrab",
    "darkolivegreen",
    "gainsboro",
    "lightgray",
    "silver",
    "darkgray",
    "lightgoldenrodyellow",
]
